apiVersion: batch/v1
kind: Job
metadata:
  name: taxi-rides-data-drift-detection-job
  namespace: default
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 600
  template:
    spec:
      containers:
      - name: taxi-rides-data-drift-detection
        image: taxi-rides-outlier-detection:my_local
        imagePullPolicy: IfNotPresent
        command: ["detect-input-data-drift", "/data"]
        volumeMounts:
        - name: local-folder
          mountPath: /data
      volumes:
      - name: local-folder
        hostPath:
          path: /run/desktop/mnt/host/c/work
          type: Directory
      restartPolicy: OnFailure
